### PR TITLE
refactor(dropdown): update items sizes and paddings

### LINKED ISSUE #1405: Dropdown discrepancies in Material, Bootstrap and Fluent themes
### Which component(s) are affected?

Dropdown

### Description

The dropdown layout styles are not the same as they're in the UI kits. The problems are in every theme, except for Indigo.

-The size of the items and header in all themes, except for Indigo should be 28/32/40 for small, medium and large.
-The margin of the prefix and suffix should be 8px, not 16px.
-The inline paddings for the items should be 16/20/24 for small, medium and large.
-The inline paddings for the header should be 8/12/16 for small, medium and large.
-The slotted icon in Fluent should be 24px for all sizes

### Reproduction

1. Open the Storybook
2. Open the Dropdown sample
3. Inspect the layout of the items in all themes, changing the --ig-size to small, medium and large

### Workaround

The implementation should be aligned with the UI kits

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

5.0.1

### Browser/OS/Node environment

All

### LINKED ISSUE #1407: Combo items height
### Which component(s) are affected?

Combo

### Description

The combo items in Material, Bootstrap and Fluent themes should be 28px, 32px, 40px for small, medium and large sizes.

### Reproduction

1. Open Storybook App
2. Open Combo Sample
3. Explore different themes and sizes

### Workaround

The sizes in the implementation should be aligned with the dropdown item sizes.

### Is this a regression?

No or unsure. This never worker, or I haven't tried before.

### Affected versions

5.0.1

### Browser/OS/Node environment

all

### PR DESCRIPTION
**Pull request by didimmova**
Closes #1405 
Closes #1407 

Inspect the combo along with the dropdown.

### CODE REVIEW

**Review by SisIvanova — CHANGES_REQUESTED** [review]
The slotted icon size in Fluent and Bootstrap themes is wrong.

**Comment by SisIvanova** [comment]
Fluent elevation should also be fixed.

**Comment by didimmova** [comment]
> The slotted icon size in Fluent and Bootstrap themes is wrong.

The design team said not to change the icons yet.

**Review by SisIvanova — APPROVED** [review]

**Comment by imincheva** [comment]
Bootstrap: Border color should be grays.300 in Dark mode

**Pull request merged**
