### PR TITLE
Banner - add themes styling 

### LINKED ISSUE #1174: Banner component
Estimated Delivery - May 31

- [x] Research
- [x] Specification
- [x] Component and tests implementation
- [x] API Documentation
- [x] Design implementation

### PR DESCRIPTION
**Pull request by desig9stein**
closes #1174

### CODE REVIEW

**Comment by imincheva** [comment]
**Bootstrap:**
- Min-width 320px hasn't been applied. Relevant for all themes.
- Not sure about this, but I believe the divider is adding up to the total height. It should be inside like it was implemented for the Nav Drawer.
- In Dark Mode the background is missing. It should be surface. The variable --banner-background seems to be inactive 
image

<br>
<br>

- Text and Icon in Dark Mode should be grays.800, not 600
image

**Comment by imincheva** [comment]
**Indigo:**
- Min-width 88px of the button is missing. In the UI kits this hasn't been implemented yet, but in both implementation it's been implemented for all themes, except for Indigo. Maybe you should discuss this with @andiesm813 as well
- I believe the border is adding up to the total height. It should be inside, similar to how it was implemented for the Nav Drawer.
- Same as all themes, min-width 320px on the whole banner hasn't been applied

**Comment by sbayreva** [comment]
**Fluent**
1. The min width of the banner should be 320px
2. The same comment for the divider from Bootstrap - "Not sure about this, but I believe the divider is adding up to the total height. It should be inside like it was implemented for the Nav Drawer"
3. There should be background in the Dark Mode - surface

**Comment by imincheva** [comment]
**Bootstrap**
- Min-width should be applied on the WHOLE Banner, not only on the message **(relevant for all themes)**
- Banner-message-color in Dark Mode is still grays.600, not 800 like mentioned in the previous comment
image

**Comment by sbayreva** [comment]
> **Fluent**
> 
> 1. The min width of the banner should be 320px
> 2. The same comment for the divider from Bootstrap - "Not sure about this, but I believe the divider is adding up to the total height. It should be inside like it was implemented for the Nav Drawer"
> 3. There should be background in the Dark Mode - surface

1. Min width 320px should be applied to the whole banner
2. Applied
3. Applied

**Comment by AnjiManova** [comment]
**Material**

- the banner border color should be grays.300 in both Dark and Light

**Comment by sbayreva** [comment]
> > **Fluent**
> > 
> > 1. The min width of the banner should be 320px
> > 2. The same comment for the divider from Bootstrap - "Not sure about this, but I believe the divider is adding up to the total height. It should be inside like it was implemented for the Nav Drawer"
> > 3. There should be background in the Dark Mode - surface
> 
> 1. Min width 320px should be applied to the whole banner
> 2. Applied
> 3. Applied

Everything from the comment is applied.

**Review by simeonoff — APPROVED** [review]

**Pull request merged**
