### PR TITLE
feat(dropdown): update indigo styles

### PR DESCRIPTION
**Pull request by SisIvanova**
Related to https://github.com/IgniteUI/igniteui-theming/issues/234

### CODE REVIEW

**Comment by didimmova** [comment]
- Shadow should be ig-elevation-2 in the dark theme.

**Comment by didimmova** [comment]
I think the outline of the active item should have outline-offset like in the angular PR

**Review by didimmova — DISMISSED** [review]

**Comment by andiesm813** [comment]
@SisIvanova i couldnt run these either.... 
image

**Comment by andiesm813** [comment]
> I think the outline of the active item should have outline-offset like in the angular PR

When you say "active" i assume it's focused.... if so, and if what you mean about the offset is that it's outlined center or outside the element, we actually have inside border.

image

**Comment by AnjiManova** [comment]
- (same comment from Angular) paddings are 3px, but the border should be placed inside (in the kit, the space between the border and the active/hover background is 2px, not sure how you are going to implement it, but we can discuss it if you want

**Comment by AnjiManova** [comment]
The overline style is wrong. A merged PR with the overline style is available, but the change is not visible in this PR.

**Comment by AnjiManova** [comment]
- the prefix has an additional 16px margin that I believe should be removed 
image

**Comment by AnjiManova** [comment]
image

**Comment by AnjiManova** [comment]
- the border radius should be fixed or something not sure what is the problem here
image

**Comment by SisIvanova** [comment]
> * the border radius should be fixed or something not sure what is the problem here
> 
> image

This issue is not related to the Indigo design updates and will be fixed in a separate PR.

**Comment by sdimchevski** [comment]
I think we are ready with the verification. @andiesm813 do you have something to add because I want to change the label to design:verified

**Comment by andiesm813** [comment]
> @SisIvanova i couldnt run these either.... image

I am still not able to run this branch (since 2 weeks ago)..... @SisIvanova i cannot verify or add anything else. Anji reviewed this thoroughly and i'm sure she didnt miss anything. So we can mark it as verified if you want @sdimchevski

**Comment by SisIvanova** [comment]
> 
> I am still not able to run this branch (since 2 weeks ago)..... @SisIvanova i cannot verify or add anything else. Anji reviewed this thoroughly and i'm sure she didnt miss anything. So we can mark it as verified if you want @sdimchevski

You couldn't run the samples because of the theming package version. Simeon created a new [PR ](https://github.com/IgniteUI/igniteui-webcomponents/pull/1224) including the Indigo design changes for the dropdown, progress, and list components. You should be able to test it without any difficulty.

**Comment by andiesm813** [comment]
@SisIvanova yes! Didi told me as well! i was able to test it now! The only thing i see weird is the Web Components version, it has like a white background color and then inside the actual dropdown appears, with the rounded corners.... In Angular it looks ok. 

image

These corners i mean

image

**Comment by SisIvanova** [comment]
> @SisIvanova yes! Didi told me as well! i was able to test it now! The only thing i see weird is the Web Components version, it has like a white background color and then inside the actual dropdown appears, with the rounded corners.... In Angular it looks ok.
> 
> image
> 
> These corners i mean
> 
> image

This problem is reproducible in all themes and will be fixed in a separate PR. I will log a new issue.

**Pull request merged**
