### PR TITLE
refactor(circular-progress): use relative font size

### PR DESCRIPTION
**Pull request by SisIvanova**
Related to IgniteUI/igniteui-angular/issues/14564

### CODE REVIEW

**Comment by imincheva** [comment]
Circular Progress seems broken

**branch:**
image

**master:**
image

**Comment by SisIvanova** [comment]
> Circular Progress seems broken
> 
> **branch:** image
> 
> **master:** image

We decided to move the circular progress diameter into its schema so we need to update the igniteui-theming version here. You can still test the changes with this PR https://github.com/IgniteUI/igniteui-theming/pull/312 or I can notify you once the version is updated.

**Comment by imincheva** [comment]
**Materal & Indigo**
Progress is cut out
image
image

Typography seems okay.

**Comment by imincheva** [comment]
**Material:**
Size should be 32x32px 
image

**Review by simeonoff — APPROVED** [review]

**Pull request merged**
