### PR TITLE
refactor(icon-button): update component styles

### LINKED ISSUE #1165: Icon Button refinement
**_All improvements should be applied for Light and Dark mode._**

### Material

Consider this feature request as a visual refinement + adding the new additional states styles ("Active" + "Focused & Active")
Link for reference [Indigo Design UI Kit for Material](https://www.figma.com/file/2dnNPqpR7K7tMrWvf3jHpO/Button?type=design&node-id=5803%3A3441&mode=design&t=DjSL3vRp1DFsgQmW-1)
image

### Fluent

Adding "Active" + "Focused & Active" states styles
[Indigo Design UI Kit for Fluent](https://www.figma.com/file/2dnNPqpR7K7tMrWvf3jHpO/Button?type=design&node-id=5804%3A6373&mode=design&t=DjSL3vRp1DFsgQmW-1)
image

### Bootstrap

Adding "Active" + "Focused & Active" states styles
[Indigo Design UI Kit for Bootstrap](https://www.figma.com/file/2dnNPqpR7K7tMrWvf3jHpO/Button?type=design&node-id=5809%3A13938&mode=design&t=DjSL3vRp1DFsgQmW-1)
image

### Indigo
Adding "Active" + "Focused & Active" states styles
[Indigo Design UI Kit for Indigo](https://www.figma.com/file/2dnNPqpR7K7tMrWvf3jHpO/Button?type=design&node-id=5810%3A21320&mode=design&t=DjSL3vRp1DFsgQmW-1)
image

### PR DESCRIPTION
**Pull request by SisIvanova**
Closes #1165 

Theming Package for testing - IgniteUI/igniteui-theming/pull/274

### CODE REVIEW

**Comment by sbayreva** [comment]
**Fluent**

1. (Light Mode ) Flat , active state icon button - when inspected the foreground says it is Primary 800 but actually there is no visible change of the foreground itself. (Tested with Figma color picker)

Screenshot 2024-06-04 at 14 42 21

2. (Dark Mode ) Flat , active state icon button - when inspected the foreground says it is Primary 100 but actually there is no visible change of the foreground itself. (Tested with Figma color picker)


3. (Light Mode ) Flat button is on hover - there is no visible change for the foreground, even though when the element is inspected it says that the foreground is primary 600. (Tested with Figma color picker)

4. (Dark Mode ) Flat button is on hover - there is no visible change for the foreground, even though when the element is inspected it says that the foreground is primary 200. (Tested with Figma color picker)

**Review by desig9stein — APPROVED** [review]

**Comment by sbayreva** [comment]
**Indigo**

1. (Dark Mode) Contained icon button- the focus border should be primary 400 with 50% opacity not white with 20% opacity as it is now
Screenshot 2024-06-05 at 10 33 23

2. (Light Mode) Outlined icon button- On Hover and Active states the color of the border should be grays. 600. There is a visual change but when inspected it says grays. 500
Screenshot 2024-06-05 at 14 16 29

**Comment by andiesm813** [comment]
Indigo icon buttons looked good to me in light and dark modes. ✅✅

**Comment by imincheva** [comment]
**Bootstrap**
By design.

**Comment by imincheva** [comment]
**Bootstrap**
- **Outlined Button:** I noticed a discrepancy in terms of the border color upon triggering active + focused state. In the first example I focus the button with tab and than hold space to trigger the active state. In this case the border color matches the background color which is by design. In the second example I focus the button with tab and than click with the mouse to trigger the active state. Here the border color doesn't match the background color, which isn't correct. 
Outlined Button_ Active   Focused
 
_I tested the same in Angular and I believe the behaviour there is accurate, no matter which combination is used to trigger active & focused state_

**Comment by sbayreva** [comment]
> **Fluent**
> 
> 1. (Light Mode ) Flat , active state icon button - when inspected the foreground says it is Primary 800 but actually there is no visible change of the foreground itself. (Tested with Figma color picker)
> 
> Screenshot 2024-06-04 at 14 42 21
> 2. (Dark Mode ) Flat , active state icon button - when inspected the foreground says it is Primary 100 but actually there is no visible change of the foreground itself. (Tested with Figma color picker)
> 3. (Light Mode ) Flat button is on hover - there is no visible change for the foreground, even though when the element is inspected it says that the foreground is primary 600. (Tested with Figma color picker)
> 4. (Dark Mode ) Flat button is on hover - there is no visible change for the foreground, even though when the element is inspected it says that the foreground is primary 200. (Tested with Figma color picker)



> **Fluent**
> 
> 1. (Light Mode ) Flat , active state icon button - when inspected the foreground says it is Primary 800 but actually there is no visible change of the foreground itself. (Tested with Figma color picker)
> 
> Screenshot 2024-06-04 at 14 42 21
> 2. (Dark Mode ) Flat , active state icon button - when inspected the foreground says it is Primary 100 but actually there is no visible change of the foreground itself. (Tested with Figma color picker)
> 3. (Light Mode ) Flat button is on hover - there is no visible change for the foreground, even though when the element is inspected it says that the foreground is primary 600. (Tested with Figma color picker)
> 4. (Dark Mode ) Flat button is on hover - there is no visible change for the foreground, even though when the element is inspected it says that the foreground is primary 200. (Tested with Figma color picker)

All applied and verified!

**Comment by imincheva** [comment]
**Bootstrap**
- After the latest changes, the active state with mouse click can't be triggered or at least it doesn't inherit the correct styles

**Comment by sbayreva** [comment]
> **Indigo**
> 
> 1. (Dark Mode) Contained icon button- the focus border should be primary 400 with 50% opacity not white with 20% opacity as it is now
> 
> Screenshot 2024-06-05 at 10 33 23
> 2. (Light Mode) Outlined icon button- On Hover and Active states the color of the border should be grays. 600. There is a visual change but when inspected it says grays. 500
> 
> Screenshot 2024-06-05 at 14 16 29

All applied and verified!

**Comment by imincheva** [comment]
**Material**
All looks good.

**Review by desig9stein — APPROVED** [review]

**Pull request merged**
