### PR TITLE
fix(calendar): Range selection a11y improvement

### LINKED ISSUE #476: Calendar accessibility improvements
## Description  
The screen reader does not read the range selection start and end dates and the current date.

### PR DESCRIPTION
**Pull request by rkaraivanov**
Closes #476

### CODE REVIEW

**Comment by ChronosSF** [comment]
nvda reads selection really well when the range is selected but while the user is choosing the range with the keyboard it reads the first selected date while the second is presented just by its position and weekday. Something like:

Selected Aug 18, 2022 . Not selected column 5 wednesday

Can we have the readout work while the user is choosing what to select as the second date in the range? Basically repeating the select behavior but leaving "unselected" so that he knows he hasn't yet confirmed the selection by just navigating with the arrow keys.

**Comment by ChronosSF** [comment]
Sounds good now, even with the windows narrator.

@desig9stein , will you be able to test it with the Mac narrator?

**Review by damyanpetev — APPROVED** [review]

**Comment by desig9stein** [comment]
I can hear the mac narrator reading the range, however, I can't hear anything about the current date. In angular calendar when I go over the current date the narrator reads something like "23 September 2022 **Current date**"

**Comment by ChronosSF** [comment]
@desig9stein , can we merge it like this and have a separate issue so that we don't block the release?

**Pull request merged**
