### PR TITLE
Themes: Update Indigo Calendar, Select, and Combo

### LINKED ISSUE #1263: Indigo Theme Calendar Improvements
After the first iteration of the handoff was designed, some styling issues appeared, and we made some changes to the handoff to address those issues In the [Indigo | Calendar Improvements branch](https://www.figma.com/design/6M8cbmxScEGL2pje8lVQgR/branch/d7A9GnXlTF9634tiHkA1yp/Calendar%2C-Date-Picker%2C-Time-Picker?m=auto&t=1bJCSm8C4DOW8OI5-1).

Most of the changes were done in the date states:
image

And these too:
image

These updates should be changed in the implemented component.

### PR DESCRIPTION
**Pull request by simeonoff**
Closes #1263

### CODE REVIEW

**Comment by yradoeva** [comment]
**Calendar** 

**Light Mode - date states**

1. **Inactive - Focused:** text color should be grays.500 (not grays.900) // triggered with :focus
GraysLightgrays 500
<br/>
Pasted Graphic 28
<br/>
Screenshot 2024-08-28 at 10 56 44
<br/>
<br/>
2. **Selected - Disabled:** text color should be white with 38% opacity (not grays.600 0.38 with 38% opacity on the span - it’s doubled) // triggered with class disabled <br/>
Specialwhite
<br/>
Screenshot 2024-08-28 at 11 00 46
<br/>
Pasted Graphic 31
<br/>
<br/>
3. **Current + Special - Hover/Focused:** text color should be primary.600 (not grays.900) // triggered with :hover / :focus

<br/>
Pasted Graphic 34
<br/>
Pasted Graphic 35
<br/>
Pasted Graphic 36
<br/>
<br/>
4. **Range: Special - Hover / Focused:** border color should be primary.600 (not primary.400) // triggered with :hover / :focus <br/>

<br/>
Pasted Graphic 38
<br/>
Pasted Graphic 39
<br/>
Pasted Graphic 40
<br/>
<br/>
5. **Range: Current + Special - Hover / Focused:** inner border (::after) color should be primary.600 (not primary.500)
Borders
<br/>
Pasted Graphic 41
<br/>
Pasted Graphic 43

<br/><br/>
**Month & Year Picker look good.**

**Comment by yradoeva** [comment]
**Calendar**

**Dark Mode - date states**

1. **Inactive - Focused:** text color should be grays.500 (not white) // triggered with :focus
<br/>
GraysDarkgrays 500
<br/>
Pasted Graphic 2
<br/>
Pasted Graphic 3
<br/>
<br/>

2. **Selected - Disabled:** text color should be white with 38% opacity (not grays.400 0.38 with 38% opacity on the span - it’s doubled) // triggered with class disabled <br/>
Specialwhite
<br/>
Pasted Graphic 5
<br/>
Pasted Graphic 6
<br/>
<br/>

3. **Current + Special - Hover/Focused:** text color should be primary.50 (not white) // triggered with :hover / :focus 
<br/>

<br/>
Pasted Graphic 8
<br/>
Pasted Graphic 9
<br/>
Pasted Graphic 10
<br/>
<br/>

4. **Range: Special - Idle:** border color should be primary.100 (not primary.500) <br/>

<br/>
Pasted Graphic 11
<br/>
Pasted Graphic 13
<br/>
<br/>

5. **Range: Special - Hover/Focused:** border color should be primary.50 (not primary.400) // triggered with :hover / :focus <br/>

<br/>
Pasted Graphic 16
<br/>
Screenshot 2024-08-28 at 9 39 42
<br/>
Pasted Graphic 17
<br/>
<br/>

6. **Range: Special - Disabled:** border color should be primary.100 38% opacity (not primary.500 38% opacity) // triggered with class disabled <br/>

<br/>
Pasted Graphic 20
<br/>
Pasted Graphic 18
<br/>
<br/>

7. **Range: Current + Special - Hover/Focused:** inner border (::after) should be primary.50 (not primary.100) // triggered with :hover / :focus <br/>

<br/>
Pasted Graphic 25
<br/>
Pasted Graphic 21
<br/>
<br/>
<br/>
<br/>

**Month & Year Picker look good.**

**Comment by imincheva** [comment]
### Combo
- The dropdown is missing paddings, they should be 3px on each side. I see they have been implemented in the dropdown already, so I'm not sure what's the issue with this.

**Comment by desig9stein** [comment]
> **Calendar**
> 
> **Light Mode - date states**
> 
> 1. **Inactive - Focused:** text color should be grays.500 (not grays.900) // triggered with :focus
> 
> GraysLightgrays 500
> Pasted Graphic 28
> Screenshot 2024-08-28 at 10 56 44
> 
> 2. **Selected - Disabled:** text color should be white with 38% opacity (not grays.600 0.38 with 38% opacity on the span - it’s doubled) // triggered with class disabled
> 
> Specialwhite
> Screenshot 2024-08-28 at 11 00 46
> Pasted Graphic 31
> 
> 3. **Current + Special - Hover/Focused:** text color should be primary.600 (not grays.900) // triggered with :hover / :focus
> 
> 
> Pasted Graphic 34
> Pasted Graphic 35
> Pasted Graphic 36
> 
> 4. **Range: Special - Hover / Focused:** border color should be primary.600 (not primary.400) // triggered with :hover / :focus
> 
> 
> Pasted Graphic 38
> Pasted Graphic 39
> Pasted Graphic 40
> 
> 5. **Range: Current + Special - Hover / Focused:** inner border (::after) color should be primary.600 (not primary.500)
> 
> Borders
> Pasted Graphic 41
> Pasted Graphic 43
> **Month & Year Picker look good.**

Inactive - Focused: text color should be grays.500 (not grays.900) // triggered with :focus 
This is not possible, the moment you go to an inactive date with the keyboard or click on it with the mouse you are navigated to the month that date belongs to. This is true for dark themes as well

**Comment by yradoeva** [comment]
**Calendar**

**Light Mode - date states** (for now I'll not check dark mode because I suppose those remarks are identical there)

1. **Current- Disabled:** text color should be grays.800 (not grays.600 0,38) - the opacity of 38% is already correctly set on the whole span
<br/>
GraysLightgrays 800
<br/>
Pasted Graphic 119
<br/>
Pasted Graphic 120

2. **Special - Disabled:** text color should be primary.500 (not grays.600 0,38) - the opacity of 38% is already correctly set on the whole span

<br/>
Pasted Graphic 122
<br/>
Pasted Graphic 120

3. **Current + Special - Disabled:** text color should be primary.500 (not grays.600 0,38) - the opacity of 38% is already correctly set on the whole span

<br/>
Pasted Graphic 125
<br/>
Pasted Graphic 126


4. **Selected + Special - Hover/Focused:** the border-color should be transparent or primary.400 (not primary.600) - in Figma we don’t have such border at all, but if there is one in the implementation, it should be the same as background (or not visible)
Pasted Graphic 129
<br/>
Pasted Graphic 128
<br/>
Pasted Graphic 131


5. **Range: Active - Disabled:** text color should be grays.600 0,38 (not grays.800)

<br/>

<br/>
Pasted Graphic 133

**Comment by yradoeva** [comment]
**Calendar**

**Light Mode - date states** (for now I'll not check dark mode because I suppose those remarks are identical there)

Selected + Current is missing the border in all 4 states (the border is transparent).

1. **Selected + Current - Idle:** border-color should be primary.100

<br/>
Pasted Graphic 136
<br/>
transparent

2. **Selected + Current - Hover/Focused:** border-color should be primary.200

<br/>
Pasted Graphic 140
<br/>
transparent
<br/>
transparent


3. **Selected + Current - Disabled:** border-color should be primary.100 with 38% opacity
Borders
<br/>
Pasted Graphic 144
<br/>
opacity  38;

**Comment by yradoeva** [comment]
**Calendar** 
**Light & Dark mode**

Date states, Month & Year Picker look good.

**Comment by imincheva** [comment]
### Grids
- Cell summary cells' height across all sizes doesn't correspond to the ones in the UI kit
- In pivot grid part of a border is missing. This is relevant for all themes, so it should probably be logged as a bug
image

- In pivot grid the padding on igx-pivot-row-dimension-header should be 6px, not 4px
image

- In GroupBy the column name and text labels should be linked to Detail 2 and Detail 1 respectively.
image
image

- The container on the image from row editing banner in small size should be 24px, not 24.5px. In the rest of the sizes it's okay, that's why I'm mentioning it here.
image

- Size of the Select in Paginator should correspond to the overall size of the grid.
- Input size here on Grid  should correspond to the size of the grid.
image

- The element which appears when you drag a header is 1px higher in all three sizes. The correct heights are 48, 40, 32 for large, medium and small respectively
- This part of the filter doesn't correspond to the design at all - paddings, margins, sizes, colors, etc.
image

- Top padding on this part should be 8px in all sizes
image

- Bottom padding here should be 4px in medium and small size. Already done in small.
image

- There should be 4px margin/gap between this title and the buttons bellow in large and medium size
image

- List paddings and gap is missing in all sizes
image



<hr>

**Light Mode**
- Background of the disabled button should be white. Currently it's set to transparent. The gap between the header and the buttons should also be 4px in large and medium size.
image

- --group-row-background should be surface, not grays.100.
- background color of the toolbar should be surface, not transparent
- border color of the toolbar should be grays.400, currently it's grays.900 30%
- background color of the paginator should be surface, currently it's transparent
- border color of the paginator should be grays.400, currently it's grays.900 30%
- Elevation 5 applied on --drag-shadow doesn't look like in the kit, probably should be updated

**Comment by desig9stein** [comment]
> ### Grids
> * Cell summary cells' height across all sizes doesn't correspond to the ones in the UI kit
> * In pivot grid part of a border is missing. This is relevant for all themes, so it should probably be logged as a bug
> 
> image
> * In pivot grid the padding on igx-pivot-row-dimension-header should be 6px, not 4px
> 
> image
> * In GroupBy the column name and text labels should be linked to Detail 2 and Detail 1 respectively.
> 
> image image
> * The container on the image from row editing banner in small size should be 24px, not 24.5px. In the rest of the sizes it's okay, that's why I'm mentioning it here.
> 
> image
> * Size of the Select in Paginator should correspond to the overall size of the grid.
> * Input size here on Grid  should correspond to the size of the grid.
> 
> image
> * The element which appears when you drag a header is 1px higher in all three sizes. The correct heights are 48, 40, 32 for large, medium and small respectively
> * This part of the filter doesn't correspond to the design at all - paddings, margins, sizes, colors, etc.
> 
> image
> * Top padding on this part should be 8px in all sizes
> 
> image
> * Bottom padding here should be 4px in medium and small size. Already done in small.
> 
> image
> * There should be 4px margin/gap between this title and the buttons bellow in large and medium size
> 
> image
> * List paddings and gap is missing in all sizes
> 
> image
> **Light Mode**
> 
> * Background of the disabled button should be white. Currently it's set to transparent. The gap between the header and the buttons should also be 4px in large and medium size.
> 
> image
> * --group-row-background should be surface, not grays.100.
> * background color of the toolbar should be surface, not transparent
> * border color of the toolbar should be grays.400, currently it's grays.900 30%
> * background color of the paginator should be surface, currently it's transparent
> * border color of the paginator should be grays.400, currently it's grays.900 30%
> * Elevation 5 applied on --drag-shadow doesn't look like in the kit, probably should be updated
> 
> **Dark Mode** PENDING

These comments are related to the Angular repo, please move them there.

**Comment by imincheva** [comment]
> * Dropdown's background, border and elevation are incorrect. Check UI kit

@simeonoff The elevation on the dropdown in dark mode should be Elevation 2. This has already been implemented for the dropdown component

**Review by SisIvanova — APPROVED** [review]

**Pull request merged**
