### PR TITLE
Indigo Themes: Updates to Toast, Stepper, Rating

### PR DESCRIPTION
**Pull request by simeonoff**

### CODE REVIEW

**Comment by AnjiManova** [comment]
**Rating**

The label padding should be 2px, not 4px.
The right padding of the symbols should be removed.
There are sizes for the symbols provided in the kit, which are - small -18x18; medium - 24x24 (default one) @andiesm813 confirm this pleases; and large - 30x30 (mentioning them because in Angular they are not the same)
The row gap should be 4px, not 5px.

**Comment by AnjiManova** [comment]
**Toast**

The component's minimum width doesn't come from us. For now, 3.25rem works well, but in the future, some changes might be suggested from our side.

The border is now outside the component, which causes it to be different in height from the one in the kit.

**Comment by andiesm813** [comment]
> **Rating**
> 
> The label padding should be 2px, not 4px. The right padding of the symbols should be removed. There are sizes for the symbols provided in the kit, which are - small -18x18; medium - 24x24 (default one) @andiesm813 confirm this pleases; and large - 30x30 (mentioning them because in Angular they are not the same) The row gap should be 4px, not 5px.

**RATING**
looks good to me @AnjiManova, the symbols sizes that is.
The rest of the component looks good! ✅

**Comment by andiesm813** [comment]
**TOAST**
Looking good! ;) ✅

**Comment by andiesm813** [comment]
**STEPPER**
It looks fine to me... Except for the "content" part, that should have more padding.... but since that's in a slot, it's not something we control, correct? 

image

**Comment by desig9stein** [comment]
> **STEPPER** It looks fine to me... Except for the "content" part, that should have more padding.... but since that's in a slot, it's not something we control, correct?
> 
> image

We can, I change it to 16px as it is in the UI kit

**Comment by AnjiManova** [comment]
**Stepper**

- Min-height of the vertical lines should be 24px
- Min-width of the horizontal lines should be 40px
- The Content should be Body 2.

More comments will be added

**Comment by desig9stein** [comment]
> **Stepper**
> 
> * Min-height of the vertical lines should be 24px
> * Min-width of the horizontal lines should be 40px
> 
> Light & Dark Mode
> 
> * Invalid state - the subtitle text color should be grays.700 and should uses other var I guess
> 
> image



> **Stepper**
> 
> * Min-height of the vertical lines should be 24px
> * Min-width of the horizontal lines should be 40px
> 
> Light & Dark Mode
> 
> * Invalid state - the subtitle text color should be grays.700 and should uses other var I guess
> 
> image

@AnjiManova For the min-height of the vertical separator we should create another issue since it is not a mater of just fixing the theme, it requires changes in the component animation.

**Comment by AnjiManova** [comment]
> > **Stepper**
> > 
> > * Min-height of the vertical lines should be 24px
> > * Min-width of the horizontal lines should be 40px
> > 
> > Light & Dark Mode
> > 
> > * Invalid state - the subtitle text color should be grays.700 and should uses other var I guess
> > 
> > image
> 
> @AnjiManova For the min-height of the vertical separator we should create another issue since it is not a mater of just fixing the theme, it requires changes in the component animation.

Agreed, a new issue to be then.

**Review by SisIvanova — DISMISSED** [review]

**Pull request merged**
